### ISSUE TITLE
Breaking change: v5.0.2 no longer supports zipping plain files

### ISSUE THREAD

**Issue by acostalima** [mockingbot/react-native-zip-archive#204]
In v5.0.2, on iOS, `zipWithPassword` no longer supports zipping plain files because the method from SSZipArchive which allows to do so is not being used anymore. Now, it is necessary to always create a directory even if you just want to zip a single file. 

Can anyone else confirm this?

Diff: https://github.com/mockingbot/react-native-zip-archive/compare/v5.0.1...v5.0.2

**Comment by plrthink** [comment]
@acostalima Can you point out which method in the SSZipArchive? I did make some changes in order to emit the progress of the zipping event, that maybe break the feature you mentioned.

**Comment by acostalima** [comment]
@plrthink, this particular one: https://github.com/mockingbot/react-native-zip-archive/compare/mockingbot:74fc1bb...mockingbot:8490ea5#diff-ed95ad7cd314cb009e2e0cf3ae17b062L127

**Comment by plrthink** [comment]
Yes, I can confirm it's a mistake here. Will fix it ASAP.

**Comment by MRDANX** [comment]
> for any size of source file , I am always getting zipped file of size 22 bytes.

It just happens in iOS, Android works fine.
This problem happen again at exact version 5.0.2, when I fall back to version 5.0.1 solved it.

**Comment by acostalima** [comment]
> > for any size of source file , I am always getting zipped file of size 22 bytes.
> 
> It just happens in iOS, Android works fine.
> This problem happen again at exact version 5.0.2, when I fall back to version 5.0.1 solved it.

Commented in the wrong issue? 😅 
Where is your quote from?

**Comment by MRDANX** [comment]
> > > for any size of source file , I am always getting zipped file of size 22 bytes.
> > 
> > 
> > It just happens in iOS, Android works fine.
> > This problem happen again at exact version 5.0.2, when I fall back to version 5.0.1 solved it.
> 
> Commented in the wrong issue? 😅
> Where is your quote from?

I think it's related to the version 5.0.2, so I commented here.😀

**Comment by acostalima** [comment]
@MRDANX, it's up to @plrthink but if it's an issue in v5.0.2 maybe it's better to create a new one to address what you have reported. I've just changed the title of this issue to be more specific.

**Comment by MRDANX** [comment]
@acostalima Since you have changed the title, now I understand what happen to me, thank you!

**Comment by acostalima** [comment]
@MRDANX, the title was kind of bad anyway to be honest 😅

**Comment by plrthink** [comment]
@acostalima @MRDANX Just published `5.0.3-beta.1`, can you try that?

**Comment by plrthink** [comment]
Fixed in 5.0.3.

**Comment by vinayn-simelabs** [comment]
Is this working now in iOS @plrthink ? I'm still getting error when trying to zip txt file
```
{
    "code": "zip_error",
    "message": "unable to zip",
    "domain": "RCTErrorDomain",
    "userInfo": null,
    "nativeStackIOS": [
    ]
}
```
